name: Deploy Jekyll site to Pages
on: push: branches: ["main"] workflow_dispatch: inputs: {}
permissions: contents: read pages: write id-token: write
concurrency: group: "pages" cancel-in-progress: false
jobs: build: runs-on: ubuntu-latest steps: - name: Checkout uses: actions/checkout@v4

- name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: '3.3'
      bundler-cache: false 
  - name: Setup Pages
    id: pages
    uses: actions/configure-pages@v5
  - name: Install Dependencies
    run: bundle install
  - name: Build with Jekyll
    # Added --trace to see full error stack
    run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --trace
    env:
      JEKYLL_ENV: production
  - name: Upload artifact
    uses: actions/upload-pages-artifact@v3
    with:
      path: ./_site
